version: '3.9'

services:
  rag-api:
    build: ./app
    container_name: rag-email-demo
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - chroma_data:/app/chroma_db
    environment:
      - CHROMA_DIR=/app/chroma_db
      - COLLECTION_NAME=email_rag_demo
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - GENERATION_MODEL=google/flan-t5-small
    restart: unless-stopped

volumes:
  chroma_data:
